### ISSUE TITLE
Raise minimum required x86 cpu feature set

### ISSUE THREAD

**Issue by codyopel** [triton/triton#16]
Require:
+ MMX
+ AES
+ SSE
+ SSE2
+ SSE3
+ SSSE3
+ SSE4
+ SSE4.1
+ SSE4.2
+ VT-x/AMD-v/VIA Virtualization

Unsupported:
+ Intel: pre-westmere
+ AMD: pre-15h
+ VIA: pre-eden x4 (released 2015/08)

It can be assumed that the required features above exist for all x86 targets.  Currently no changes will be made, this just exists as a guideline for future plans.

**Comment by wkennington** [comment]
All of these are now enabled.
