### ISSUE TITLE
polkit 0.114 segfaults

### ISSUE THREAD

**Issue by codyopel** [triton/triton#90]

**Comment by wkennington** [comment]
Fixed by https://github.com/triton/triton/commit/14527a1a074025dd4e673c74fadff39edf369189

**Comment by wkennington** [comment]
./result/lib/polkit-1/polkitd
Successfully changed to user polkitd
19:07:02.143: Loading rules from directory /etc/polkit-1/rules.d
19:07:02.143: Error opening rules directory: Error opening directory ?/etc/polkit-1/rules.d?: No such file or directory (g-file-error-quark, 4)
19:07:02.143: Loading rules from directory /run/current-system/sw/share/polkit-1/rules.d
19:07:02.143: Error opening rules directory: Error opening directory ?/run/current-system/sw/share/polkit-1/rules.d?: No such file or directory (g-file-error-quark, 4)
19:07:02.143: Finished loading, compiling and executing 0 rules
Entering main event loop
Connected to the system bus
19:07:02.144: Lost the name org.freedesktop.PolicyKit1 - exiting
Shutting down
Exiting with code 0
